import { Providers } from "./components/Providers"
import "./page.css"
export const metadata = {
  title: 'MERCH.CO',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
